version: "3"

services:
  postgresql:
    image: postgres:14
    hostname: postgresql
    env_file:
      - ./config/database.env
    environment:
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    volumes:
      - postgres_db:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "15432:5432"
    restart: always

  backend:
    build: .
    hostname: acb-backend
    depends_on:
      postgresql:
        condition: service_started
    env_file:
      - ./config/database.env
    environment:
      RUST_LOG: "info"
    ports:
      - "8085:8080"
    restart: always

volumes:
  postgres_db:
    driver: local
