version: "3"

services:
  postgresql:
    image: postgres:14
    hostname: postgresql
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: --encoding=UTF8
    volumes:
      - dev:/var/lib/postgresql/data
      - ../initdb:/docker-entrypoint-initdb.d

  dev:
    build:
      context: .
      args:
        LOCAL_UID: "1000"
        LOCAL_USER: vscode
        LOCAL_PASSWORD: vscode
    hostname: dev
    depends_on:
      postgresql:
        condition: service_started
    environment:
      POSTGRES_URL: postgresql://db_user:db_pass@postgresql:5432/test_db
      RUST_LOG: "info"
    ports:
      - "8080:8080"
    volumes:
      - ../:/home/vscode/atcoder-bingo/
    command: /bin/sh -c "while sleep 1000; do :; done"

volumes:
  dev:
    driver: local
