version: "3.5"

services:
  postgresql:
    image: postgres:14
    hostname: postgresql
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: test_db
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "15432:5432"
    restart: always
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
      - ../initdb:/docker-entrypoint-initdb.d

  backend-development:
    build: .
    hostname: acb-backend-development
    depends_on:
      - postgresql
    environment:
      POSTGRES_URL: postgresql://db_user:db_pass@postgresql:5432/test_db
      RUST_LOG: "info"
    ports:
      - "8080:8080"
    volumes:
      - ../:/work/
    working_dir: /work/
    command: /bin/sh -c "while sleep 1000; do :; done"
